/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import services.NhanVienService;
import services.serviceImpl.NhanVienServiceImpl;
import customModels.NhanVienCustom;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author window
 */
public class TryingTwoNhanVienFrom extends javax.swing.JFrame {

    /**
     * Creates new form TryingTwoFrom
     */
    private DefaultTableModel model = new DefaultTableModel();
    private List<NhanVienCustom> listQLNhanVien;
    private NhanVienService nhanVienService;

    public TryingTwoNhanVienFrom() {
        initComponents();
        tbNhanVien.setModel(model);
        String[] hearder = {"Mã", "Tên", "SĐT", "Địa chỉ"};
        model.setColumnIdentifiers(hearder);
        nhanVienService = new NhanVienServiceImpl();
        listQLNhanVien = new ArrayList<>();
        listQLNhanVien = nhanVienService.getList();
        showData(listQLNhanVien);
    }

    public void showData(List<NhanVienCustom> qlnv) {
        model.setRowCount(0);
        for (NhanVienCustom qLNhanVien : qlnv) {
            model.addRow(qLNhanVien.toRowData1());
        }
    }

    public void fillDataToTable(int index) {
        NhanVienCustom qlnv = listQLNhanVien.get(index);
        txtMa.setText(qlnv.getMa());
        txtTen.setText(qlnv.getHo() + " " + qlnv.getTenDem() + " " + qlnv.getTen());
        txtSdt.setText(qlnv.getSdt());
        txtDiaChi.setText(qlnv.getDiaChi());
    }

    public NhanVienCustom checkValidate() {
        NhanVienCustom qlnv = new NhanVienCustom();
        String ma = txtMa.getText().trim();
        String ten = txtTen.getText().trim();
        String sdt = txtSdt.getText().trim();
        String diaChi = txtDiaChi.getText().trim();
        if (ma.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã không được trống");
            return null;
        }
        if (ten.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên không được trống");
            return null;
        }
        if (sdt.equals("")) {
            JOptionPane.showMessageDialog(this, "SDT không được trống");
            return null;
        }
        if (!sdt.matches("0+\\d{9}")) {
            JOptionPane.showMessageDialog(this, "Sai định dạng sdt 0 + 9 số");
            return null;
        }
        if (diaChi.equals("")) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được trống");
            return null;
        }
        int cuoi = ten.lastIndexOf(" ");
        int dau = ten.indexOf(" ");
        String tenNew = ten.substring(cuoi, ten.length());
        String tenDem = ten.substring(dau, cuoi);
        String ho = ten.substring(0, dau);

        qlnv.setTen(tenNew);
        qlnv.setTenDem(tenDem);
        qlnv.setHo(ho);
        qlnv.setMa(ma);
        qlnv.setSdt(sdt);
        qlnv.setDiaChi(diaChi);
        return qlnv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        them = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.jLabel2.text")); // NOI18N

        txtMa.setText(org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.txtMa.text")); // NOI18N

        txtTen.setText(org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.txtTen.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.jLabel3.text")); // NOI18N

        txtSdt.setText(org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.txtSdt.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.jLabel5.text")); // NOI18N

        txtSearch.setText(org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.txtSearch.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.jLabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(search, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.search.text")); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(them, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.them.text")); // NOI18N
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(sua, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.sua.text")); // NOI18N
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(xoa, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.xoa.text")); // NOI18N
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(TryingTwoNhanVienFrom.class, "TryingTwoNhanVienFrom.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane2.setViewportView(txtDiaChi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtSdt))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(search))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(them)
                .addGap(31, 31, 31)
                .addComponent(sua)
                .addGap(33, 33, 33)
                .addComponent(xoa)
                .addGap(41, 41, 41)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(sua)
                    .addComponent(xoa)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        txtDiaChi.setText("");
        txtMa.setText("");
        txtSdt.setText("");
        txtSearch.setText("");
        txtTen.setText("");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String find = txtSearch.getText();
        if(find.isEmpty()){
            showData(nhanVienService.getList());
        }else{
            showData(nhanVienService.getListBySdt(find));
        }
    }//GEN-LAST:event_searchActionPerformed

    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        int s = tbNhanVien.getSelectedRow();
        fillDataToTable(s);
    }//GEN-LAST:event_tbNhanVienMouseClicked

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        if (nhanVienService.checkMa(txtMa.getText())) {
            JOptionPane.showMessageDialog(this, "Mã trùng");
            return;
        }

        NhanVienCustom qlnv = checkValidate();
        if (qlnv == null) {
            return;
        }
        
        nhanVienService.them(qlnv);
        listQLNhanVien = nhanVienService.getList();;
        showData(listQLNhanVien);
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_themActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed

        NhanVienCustom qlnv = checkValidate();
        if (qlnv == null) {
            return;
        }
        int s = tbNhanVien.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập 1 dòng để sửa");
            return;
        }
        NhanVienCustom ql = listQLNhanVien.get(s);
        qlnv.setId(ql.getId());
        qlnv.setMa(ql.getMa());
        nhanVienService.sua(qlnv);
        listQLNhanVien = nhanVienService.getList();;
        showData(listQLNhanVien);
        JOptionPane.showMessageDialog(this, "Sửa thành công");
    }//GEN-LAST:event_suaActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        int s = tbNhanVien.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng để xóa");
            return;
        }
        nhanVienService.xoa(listQLNhanVien.get(s).getId());
        listQLNhanVien.remove(s);
        listQLNhanVien = nhanVienService.getList();
        showData(listQLNhanVien);
        JOptionPane.showMessageDialog(this, "Xóa thành công");
    }//GEN-LAST:event_xoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TryingTwoNhanVienFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TryingTwoNhanVienFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TryingTwoNhanVienFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TryingTwoNhanVienFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TryingTwoNhanVienFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search;
    private javax.swing.JButton sua;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JButton them;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTen;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
