/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import services.ChiTietSanPhamService;
import services.serviceImpl.ChiTietSanPhamServiceImpl;
import customModels.ChiTietSPCustom;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author window
 */
public class TryingThreeCTSanPhamForm extends javax.swing.JFrame {

    /**
     * Creates new form TryingThreeCTSanPhamForm
     */
    private DefaultTableModel model = new DefaultTableModel();
    private ChiTietSanPhamService chiTietSanPhamService = new ChiTietSanPhamServiceImpl();
    private List<ChiTietSPCustom> listQlCTSanPham = new ArrayList<>();

    public TryingThreeCTSanPhamForm() {
        initComponents();
        tbCTSanPham.setModel(model);
        String[] hearder = {"ID", "Năm bh", "Mô tả", "SL tồn", "Giá nhập", "Trạng thái"};
        model.setColumnIdentifiers(hearder);
        listQlCTSanPham = chiTietSanPhamService.getList();
        showData(listQlCTSanPham);
    }

    public void showData(List<ChiTietSPCustom> qlct) {
        model.setRowCount(0);
        for (ChiTietSPCustom qLChiTietSP : qlct) {
            model.addRow(qLChiTietSP.toRowData1());
        }
    }

    public void fillDataToTable(int index) {
        ChiTietSPCustom qlctsp = listQlCTSanPham.get(index);
        txtNamBh.setText(qlctsp.getNamBH() + "");
        txtMota.setText(qlctsp.getMoTa() + "");
        txtSlTon.setText(qlctsp.getSoLuongTon() + "");
        txtGiaNhap.setText(qlctsp.getGiaNhap() + "");
    }

    public ChiTietSPCustom checkValidate() {
        String nam = txtNamBh.getText();
        String moTa = txtMota.getText();
        String sLTon = txtSlTon.getText();
        String giaNhap = txtGiaNhap.getText();
        if (nam.isEmpty() || moTa.isEmpty() || sLTon.isEmpty() || giaNhap.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống bất kì trường nào");
            return null;
        }
        ChiTietSPCustom qlctsp = new ChiTietSPCustom();
        qlctsp.setNamBH(Integer.parseInt(nam));
        qlctsp.setMoTa(moTa);
        qlctsp.setSoLuongTon(Integer.parseInt(sLTon));
        qlctsp.setGiaNhap(BigDecimal.valueOf(Double.parseDouble(giaNhap)));
        return qlctsp;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamBh = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSlTon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbbSearch = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        search = new javax.swing.JButton();
        them = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCTSanPham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.jLabel2.text")); // NOI18N

        txtNamBh.setText(org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.txtNamBh.text")); // NOI18N

        txtGiaNhap.setText(org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.txtGiaNhap.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.jLabel4.text")); // NOI18N

        txtSlTon.setText(org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.txtSlTon.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.jLabel6.text")); // NOI18N

        cbbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", " ", " " }));

        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane1.setViewportView(txtMota);

        org.openide.awt.Mnemonics.setLocalizedText(search, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.search.text")); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(them, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.them.text")); // NOI18N
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(sua, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.sua.text")); // NOI18N
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(xoa, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.xoa.text")); // NOI18N
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(TryingThreeCTSanPhamForm.class, "TryingThreeCTSanPhamForm.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tbCTSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCTSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCTSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCTSanPham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(cbbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(search)
                        .addGap(142, 142, 142))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNamBh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSlTon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(them)
                                .addGap(63, 63, 63)
                                .addComponent(sua)
                                .addGap(55, 55, 55)
                                .addComponent(xoa)))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamBh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSlTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(sua)
                    .addComponent(xoa)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearForm() {
        txtGiaNhap.setText("");
        txtMota.setText("");
        txtNamBh.setText("");
        txtSlTon.setText("");
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        clearForm();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbCTSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCTSanPhamMouseClicked
        int s = tbCTSanPham.getSelectedRow();
        fillDataToTable(s);
    }//GEN-LAST:event_tbCTSanPhamMouseClicked

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        ChiTietSPCustom ql = checkValidate();
        if (ql == null) {
            return;
        }
        chiTietSanPhamService.them(ql);
        showData(chiTietSanPhamService.getList());
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        clearForm();
    }//GEN-LAST:event_themActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        ChiTietSPCustom ql = checkValidate();
        if (ql == null) {
            return;
        }
        int s = tbCTSanPham.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 sản phẩm để sửa");
            return;
        }
        ChiTietSPCustom qlctsp = listQlCTSanPham.get(s);
        ql.setId(qlctsp.getId());
        chiTietSanPhamService.sua(ql);

        showData(chiTietSanPhamService.getList());
        JOptionPane.showMessageDialog(this, "Sửa thành công");
        clearForm();
    }//GEN-LAST:event_suaActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        int s = tbCTSanPham.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 sản phẩm để xóa");
            return;
        }
        chiTietSanPhamService.xoa(listQlCTSanPham.get(s).getId());
        showData(chiTietSanPhamService.getList());
        JOptionPane.showMessageDialog(this, "Xóa thành công");
        clearForm();
    }//GEN-LAST:event_xoaActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String namBH = cbbSearch.getSelectedItem().toString();
        System.out.println(namBH);
        int TestTreatmentID = Integer.parseInt(namBH);
        listQlCTSanPham = chiTietSanPhamService.getListByNamBH(TestTreatmentID);
        if (listQlCTSanPham.size() == 0) {
            showData(chiTietSanPhamService.getList());
        } else {
            showData(listQlCTSanPham);
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TryingThreeCTSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TryingThreeCTSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TryingThreeCTSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TryingThreeCTSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TryingThreeCTSanPhamForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbSearch;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search;
    private javax.swing.JButton sua;
    private javax.swing.JTable tbCTSanPham;
    private javax.swing.JButton them;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtNamBh;
    private javax.swing.JTextField txtSlTon;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
