/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.ChucVu;
import DomainModels.HoaDon;
import DomainModels.KhachHang;
import DomainModels.NhanVien;
import Repositories.KhachHangRepository;
import Services.ServiceImpl.HoaDonServiceImpl;
import Services.ServiceImpl.KhachHangServiceImpl;
import Services.ServiceImpl.NhanVienServiceImpl;
import java.sql.Date;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class HoaDonForm extends javax.swing.JFrame {

    /**
     * Creates new form ChucVuView
     */
    private HoaDonServiceImpl qlhd;

    public HoaDonForm() {
        initComponents();
        qlhd = new HoaDonServiceImpl();
        NhanVienServiceImpl qlnv = new NhanVienServiceImpl();
        List<NhanVien> nhanvien = qlnv.getList();
        for (NhanVien nhanVien : nhanvien) {
            String manv = "";
            manv = nhanVien.getMa();
            this.cbbIDNV.addItem(manv);
        }
        KhachHangServiceImpl qlkh = new KhachHangServiceImpl();
        List<KhachHang> khachhang = qlkh.getList();
        for (KhachHang khachHang : khachhang) {
            String makh = "";
            makh = khachHang.getMa();
            this.cbbIdKH.addItem(makh);
        }
        this.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenNguoiNhan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoaForm = new javax.swing.JButton();
        txtMa = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtNgayTao = new javax.swing.JTextField();
        txtNgayThanhToan = new javax.swing.JTextField();
        txtNgayShip = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtNgayNhan = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        cbbIDNV = new javax.swing.JComboBox<>();
        cbbIdKH = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbbTinhTrang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("IDKH");

        jLabel2.setText("IDNV");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Hoa Don");

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma", "NgayTao", "NgayThanhToan", "NgayShip", "NgayNhan", "TinhTrang", "TenNguoiNhan", "DiaChi", "Sdt", "MaKH", "MaNV"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoaForm.setText("XoaForm");
        btnXoaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaFormActionPerformed(evt);
            }
        });

        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");

        txtNgayShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayShipActionPerformed(evt);
            }
        });

        cbbIdKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbIdKHActionPerformed(evt);
            }
        });

        jLabel4.setText("NgayNhan");

        jLabel5.setText("NgayShip");

        jLabel6.setText("NgayThanhToan");

        jLabel7.setText("NgayTao");

        jLabel8.setText("Ma");

        jLabel9.setText("TenNguoiNhan");

        jLabel10.setText("TinhTrang");

        jLabel11.setText("DiaChi");

        jLabel12.setText("Sdt");

        cbbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cho Thanh Toan", "Da thanh toan", "Da Huy" }));
        cbbTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTinhTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbIdKH, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(txtNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtNgayShip, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                                            .addComponent(txtNgayThanhToan))))
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtSdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtTenNguoiNhan, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSearch)
                                    .addComponent(btnXoaForm)
                                    .addComponent(btnSua)
                                    .addComponent(btnXoa)
                                    .addComponent(btnThem))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbbIdKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbbIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnSearch)
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(cbbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNguoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaForm)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = this.tblHoaDon.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Ban phai chon mot dong!");
            return;
        }
        String ma= this.tblHoaDon.getValueAt(row, 0).toString();
        UUID id = null;
        List<HoaDon> ls = this.qlhd.getList();
           for (HoaDon l : ls) {
            if(l.getMa().equalsIgnoreCase(ma)){
                id = l.getId();
                break;
            }
        }
        this.qlhd.Delete(id);
        this.loadTable();
        this.clearForm();
        JOptionPane.showMessageDialog(this, "Xoa thanh cong");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        HoaDon hd = this.getFormData();
        if(hd == null){
            return;
        }
        this.qlhd.Insert(hd);
        this.clearForm();
        this.loadTable();
        JOptionPane.showMessageDialog(this, "Them thanh cong");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        HoaDon hd = this.getFormData();
        if(hd == null){
            return;
        }
        int row = this.tblHoaDon.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Ban phai chon mot dong");
            return;
        }
         String ma = this.tblHoaDon.getValueAt(row, 0).toString();
            UUID id = null;
        List<HoaDon> ls = this.qlhd.getList();
           for (HoaDon l : ls) {
            if(l.getMa().equalsIgnoreCase(ma)){
                id = l.getId();
                break;
            }
        }
         
           
        this.qlhd.Update(hd, id);
        this.loadTable();
        this.clearForm();
        JOptionPane.showMessageDialog(this, "Sua thanh cong");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
      int row = this.tblHoaDon.getSelectedRow();
      if(row == -1){
          return;
      }

        String ma = this.tblHoaDon.getValueAt(row, 0).toString();
        String ngaytao = this.tblHoaDon.getValueAt(row, 1).toString();
        String ngaythanhtoan = this.tblHoaDon.getValueAt(row, 2).toString();
        String ngayship = this.tblHoaDon.getValueAt(row, 3).toString();
        String ngaynhap = this.tblHoaDon.getValueAt(row, 4).toString();
        String tinhTrang = this.tblHoaDon.getValueAt(row, 5).toString();
        String tennn = this.tblHoaDon.getValueAt(row, 6).toString();
        String  diachi = this.tblHoaDon.getValueAt(row, 7).toString();
        String sdt = this.tblHoaDon.getValueAt(row, 8).toString();
        String idKH = this.tblHoaDon.getValueAt(row, 9).toString();
     String idNV = this.tblHoaDon.getValueAt(row, 10).toString();
//        this.cbbIDNV.setSelectedItem(idNV);
//        this.cbbIdKH.setSelectedItem(idNV);
        this.txtMa.setText(ma);
        this.txtTenNguoiNhan.setText(tennn);
        this.txtNgayTao.setText(ngaytao);
        this.txtNgayShip.setText(ngaytao);
        this.txtNgayThanhToan.setText(ngaythanhtoan);
        this.txtNgayNhan.setText(ngaynhap);
        this.cbbTinhTrang.setSelectedItem(tinhTrang);
        this.txtDiaChi.setText(diachi);
        this.txtSdt.setText(sdt);
        this.cbbIdKH.setSelectedItem(idKH);
        this.cbbIDNV.setSelectedItem(idNV);
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnXoaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaFormActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnXoaFormActionPerformed

    private void txtNgayShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayShipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayShipActionPerformed

    private void cbbIdKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbIdKHActionPerformed
//        NhanVienInterface qlnv = new imNhanVien();
//        List<NhanVien> nhanvien = qlnv.getList();
//        for (NhanVien nhanVien : nhanvien) {
//            String manv = "";
//            manv = String.valueOf(nhanVien.getId());
//          
//        }
    }//GEN-LAST:event_cbbIdKHActionPerformed

    private void cbbTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTinhTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTinhTrangActionPerformed
    
    public HoaDon getFormData(){
        String ma = this.txtMa.getText();
        String ngayTao = this.txtNgayTao.getText();
        String ngayThanhToan = this.txtNgayThanhToan.getText();
        String ngayNhan = this.txtNgayNhan.getText();
        String ngayShip = this.txtNgayShip.getText();
        String tinhTrang = this.cbbTinhTrang.getSelectedItem().toString();
        String tenNguoiNhan = this.txtTenNguoiNhan.getText();
        String diaChi = this.txtDiaChi.getText();
        String sdt = this.txtSdt.getText();
        String makh = this.cbbIdKH.getSelectedItem().toString();
        String manv = this.cbbIDNV.getSelectedItem().toString();
        KhachHang idKh = null;
        NhanVien idNV = null;
        NhanVienServiceImpl qlnv = new NhanVienServiceImpl();
        KhachHangServiceImpl qlkh = new KhachHangServiceImpl();
        List<KhachHang> ls = qlkh.getList();
        for (KhachHang l : ls) {
            if(l.getMa().equalsIgnoreCase(makh)){
                idKh = l;
            }
        }
        
        List<NhanVien> list = qlnv.getList();
        for (NhanVien l : list) {
            if(l.getMa().equalsIgnoreCase(manv)){
                idNV = l;
            }
        }
        
        
        int tinhtrangg = 0;
        if(tinhTrang.equalsIgnoreCase("Cho thanh toan")){
           tinhtrangg =1;
            
        }else if(tinhTrang.equalsIgnoreCase("Da thanh toan")){
            tinhtrangg = 2;
        }else{
            tinhtrangg = 0;
        }
        
       
        
        Date ngaynhann = null;
        Date ngaytaoo = null;
        Date ngayshipp = null;
        Date ngaythanhtoann = null;
        try {
            ngaynhann = Date.valueOf(ngayNhan);
            ngaytaoo = Date.valueOf(ngayTao);
            ngayshipp = Date.valueOf(ngayShip);
            ngaythanhtoann = Date.valueOf(ngayThanhToan);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sai dinh dang ngay thang");
            e.printStackTrace();
        }
        if(ma.trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Khong duoc de trong !");
            return null;
        }
            if(ngayNhan.trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Khong duoc de trong !");
            return null;
        }
          if(ngayTao.trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Khong duoc de trong !");
            return null;
        }
            if(ngayShip.trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Khong duoc de trong !");
            return null;
        }
             if(ngayThanhToan.trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Khong duoc de trong !");
            return null;
        }
            if(sdt.trim().length() == 0 || sdt.trim().length() != 10){
            JOptionPane.showMessageDialog(this, "Khong duoc de trong va SDt phai bang 10 so");
            return null;
        }
             if(diaChi.trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Khong duoc de trong !");
            return null;
        }
            if(tenNguoiNhan.trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Khong duoc de trong !");
            return null;
        }
             if(tinhTrang.trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Khong duoc de trong !");
            return null;
        }
           
          HoaDon hoadon = null;
          hoadon = new HoaDon(ma, ngaytaoo, ngaythanhtoann, ngayshipp, ngaynhann, tinhtrangg, tenNguoiNhan, diaChi, sdt, idKh, idNV);
          return hoadon;
        
    
    }
    private void clearForm(){
        this.txtDiaChi.setText("");
        this.txtMa.setText("");
        this.txtTenNguoiNhan.setText("");
        this.txtNgayShip.setText("");
        this.txtNgayNhan.setText("");
        this.txtNgayTao.setText("");
        this.txtNgayThanhToan.setText("");
        this.txtSdt.setText("");
        this.cbbIDNV.setSelectedIndex(0);
        this.cbbIdKH.setSelectedIndex(0);
        this.cbbTinhTrang.setSelectedIndex(0);
        
    }
    private void loadTable(){
        DefaultTableModel dtm = (DefaultTableModel) this.tblHoaDon.getModel();
        dtm.setRowCount(0);
        List<HoaDon> ds = this.qlhd.getList() ;
        for (HoaDon d : ds) {
            Object[] rowData = {
                d.getMa(),
                d.getNgayTao(),
                d.getNgayThanhToan(),
                d.getNgayShip(),
                d.getNgayNhan(),
                d.getTinhTrang() == 0 ? "Da thanh toan" : d.getTinhTrang() == 1 ? "Chua thanh toan" : "Da huy" ,
                d.getTenNguoiNhan(),
                d.getDiaChhi(),
                d.getSdt(),
                d.getIdKH().getMa(),
                d.getIdNhanVien().getMa()
            };
            dtm.addRow(rowData);
        }
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaForm;
    private javax.swing.JComboBox<String> cbbIDNV;
    private javax.swing.JComboBox<String> cbbIdKH;
    private javax.swing.JComboBox<String> cbbTinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgayNhan;
    private javax.swing.JTextField txtNgayShip;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNgayThanhToan;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenNguoiNhan;
    // End of variables declaration//GEN-END:variables
}
