package Views;

import DomainModels.NhanVien;
import Utilities.Auth;
import Utilities.MsgBox;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import Services.NhanVienService;
import Services.ServiceImpl.NhanVienServiceImpl;
import java.util.UUID;

public class LoginJDialog extends javax.swing.JDialog {

    NhanVienService nhanVienService;
    public LoginJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Login");
        nhanVienService = new NhanVienServiceImpl();
        lblhidenEye.setVisible(false);
        setLocationRelativeTo(parent);
    }

    void exit() {
        if (MsgBox.confirm(this, "Do you want to exit the app?")) {
            System.exit(0);
        }
    }

    void login() {
        String manv = txtUser.getText();
        String password = new String(txtPassword.getPassword());
        NhanVien nhanVien = nhanVienService.getNhanVienByMa(manv);
        if (nhanVien == null) {
            MsgBox.alert(this, "Wrong username!");
        } else if (!password.equals(nhanVien.getMatKhau())) {
            MsgBox.alert(this, "Wrong password!");
        } else {
            Auth.user = nhanVien;
            this.dispose();
            new GreetJDialog(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPwdIcon = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lbleye = new javax.swing.JLabel();
        lblhidenEye = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlLeft.setBackground(new java.awt.Color(204, 204, 204));

        lblImage.setBackground(new java.awt.Color(204, 204, 204));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon("D:\\ranh\\demoSampleProject\\src\\main\\resources\\icons\\login.png")); // NOI18N

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setToolTipText("");
        txtUser.setBorder(null);
        pnlRight.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 204, 204));
        pnlRight.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 200, 10));

        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        pnlRight.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 200, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 204, 204));
        pnlRight.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, 10));

        lblPwdIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPwdIcon.setIcon(new javax.swing.ImageIcon("D:\\ranh\\demoSampleProject\\src\\main\\resources\\icons\\Lock.png")); // NOI18N
        pnlRight.add(lblPwdIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 30, 40));

        lblUserIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserIcon.setIcon(new javax.swing.ImageIcon("D:\\ranh\\demoSampleProject\\src\\main\\resources\\icons\\User.png")); // NOI18N
        pnlRight.add(lblUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 30, 40));

        lblTitle.setFont(new java.awt.Font("Zilla Slab Medium", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("LOGIN");
        pnlRight.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 220, 40));

        lbleye.setIcon(new javax.swing.ImageIcon("D:\\ranh\\demoSampleProject\\src\\main\\resources\\icons\\eye-16.png")); // NOI18N
        lbleye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbleyeMouseReleased(evt);
            }
        });
        pnlRight.add(lbleye, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 20, 20));

        lblhidenEye.setIcon(new javax.swing.ImageIcon("D:\\ranh\\demoSampleProject\\src\\main\\resources\\icons\\hidden-eye-16.png")); // NOI18N
        lblhidenEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblhidenEyeMouseReleased(evt);
            }
        });
        pnlRight.add(lblhidenEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 20, 20));

        kButton3.setText("Sign in");
        kButton3.setToolTipText("");
        kButton3.setFont(new java.awt.Font("Zilla Slab", 1, 14)); // NOI18N
        kButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kButton3.setkBackGroundColor(new java.awt.Color(204, 255, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 204, 204));
        kButton3.setkHoverStartColor(new java.awt.Color(204, 204, 255));
        kButton3.setkSelectedColor(new java.awt.Color(255, 255, 204));
        kButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        pnlRight.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 110, 60));

        kButton4.setText("Exit");
        kButton4.setToolTipText("");
        kButton4.setFont(new java.awt.Font("Zilla Slab", 1, 14)); // NOI18N
        kButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kButton4.setkBackGroundColor(new java.awt.Color(255, 204, 204));
        kButton4.setkEndColor(new java.awt.Color(255, 153, 153));
        kButton4.setkHoverEndColor(new java.awt.Color(0, 255, 153));
        kButton4.setkHoverForeGround(new java.awt.Color(0, 255, 51));
        kButton4.setkHoverStartColor(new java.awt.Color(204, 255, 204));
        kButton4.setkSelectedColor(new java.awt.Color(255, 204, 204));
        kButton4.setkStartColor(new java.awt.Color(255, 0, 102));
        kButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        pnlRight.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 110, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnSignInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseReleased
    }//GEN-LAST:event_btnSignInMouseReleased

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
    }//GEN-LAST:event_btnExitMouseReleased

    private void lbleyeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleyeMouseReleased
        lbleye.setVisible(false);
        lblhidenEye.setVisible(true);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lbleyeMouseReleased

    private void lblhidenEyeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhidenEyeMouseReleased
        lblhidenEye.setVisible(false);
        lbleye.setVisible(true);
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_lblhidenEyeMouseReleased

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed

    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        login();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        exit();
    }//GEN-LAST:event_kButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        NhanVien nv = new NhanVien();
        
        System.out.println(nv.getId()+ nv.getMa());
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginJDialog dialog = new LoginJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPwdIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lbleye;
    private javax.swing.JLabel lblhidenEye;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
